### PR TITLE
Add failing test for fetching duplicate edges

### PR DESCRIPTION
**Pull request by mxstbr**
This fails even though it probably shouldn't? Reference PR: #91

This test boils down to fetching the first page with `first: 2`:

one
two

and then fetching the second page with `first: 2, after: one`, which returns

two
three

which should result in

one
two
three

however it results in

one
two

which does not make any sense whatsoever.

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
The problem here is that we write this to cache as Query.items(after: "1")

**Comment by mxstbr** [comment]
I am not quite sure what that means, is my test incorrect? 😅

**Comment by JoviDeCroock** [comment]
It's not incorrect if this situation occurs but what will happen is your second write will be stores as store.links.items(after: "1") while you want to try and query store.links.items(after: "2") judging on your endCursor of your first write.

**Comment by kitten** [comment]
Merged into the mainline branch and passing https://github.com/FormidableLabs/urql-exchange-graphcache/pull/91/commits/0fc92037451327c8f14a76ce2aa32fbfb08a1fe4

**Pull request closed without merging**
